/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PlatformStats = IDL.Record({
  'totalScans' : IDL.Nat,
  'activeAlerts' : IDL.Nat,
  'threatsDetected' : IDL.Nat,
});
export const ModuleCount = IDL.Record({
  'moduleName' : IDL.Text,
  'count' : IDL.Nat,
});
export const RiskLevel = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'critical' : IDL.Null,
  'medium' : IDL.Null,
});
export const ScanRecord = IDL.Record({
  'id' : IDL.Nat,
  'inputSummary' : IDL.Text,
  'resultScore' : IDL.Nat,
  'moduleName' : IDL.Text,
  'timestamp' : IDL.Int,
  'riskLevel' : RiskLevel,
});
export const ThreatEntry = IDL.Record({
  'id' : IDL.Nat,
  'description' : IDL.Text,
  'threatType' : IDL.Text,
  'timestamp' : IDL.Int,
  'severity' : IDL.Text,
  'location' : IDL.Text,
});

export const idlService = IDL.Service({
  'analyzeText' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'checkPasswordStrength' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'getPlatformStats' : IDL.Func([], [PlatformStats], ['query']),
  'getScanCountsByModule' : IDL.Func([], [IDL.Vec(ModuleCount)], []),
  'getScanHistory' : IDL.Func([], [IDL.Vec(ScanRecord)], ['query']),
  'getThreatFeed' : IDL.Func([], [IDL.Vec(ThreatEntry)], ['query']),
  'submitScan' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, RiskLevel],
      [IDL.Nat],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PlatformStats = IDL.Record({
    'totalScans' : IDL.Nat,
    'activeAlerts' : IDL.Nat,
    'threatsDetected' : IDL.Nat,
  });
  const ModuleCount = IDL.Record({
    'moduleName' : IDL.Text,
    'count' : IDL.Nat,
  });
  const RiskLevel = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'critical' : IDL.Null,
    'medium' : IDL.Null,
  });
  const ScanRecord = IDL.Record({
    'id' : IDL.Nat,
    'inputSummary' : IDL.Text,
    'resultScore' : IDL.Nat,
    'moduleName' : IDL.Text,
    'timestamp' : IDL.Int,
    'riskLevel' : RiskLevel,
  });
  const ThreatEntry = IDL.Record({
    'id' : IDL.Nat,
    'description' : IDL.Text,
    'threatType' : IDL.Text,
    'timestamp' : IDL.Int,
    'severity' : IDL.Text,
    'location' : IDL.Text,
  });
  
  return IDL.Service({
    'analyzeText' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'checkPasswordStrength' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'getPlatformStats' : IDL.Func([], [PlatformStats], ['query']),
    'getScanCountsByModule' : IDL.Func([], [IDL.Vec(ModuleCount)], []),
    'getScanHistory' : IDL.Func([], [IDL.Vec(ScanRecord)], ['query']),
    'getThreatFeed' : IDL.Func([], [IDL.Vec(ThreatEntry)], ['query']),
    'submitScan' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, RiskLevel],
        [IDL.Nat],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };